#%RAML 1.0
# From https://github.com/mulesoft/api-console/blob/master/dist/examples/instagram.raml
---
title: Index
documentation:
  - title: API index
    content: |
      [first RAML](first-raml.html)
